routes/admin.php
<?php

Route::auth();

Route::group(['middleware' => ['auth']], function () {

    Route::get('/', 'UserController@index')->name('home');

    Route::post('reorder', 'HomeController@reorder');

    //Users
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('create', 'UserController@create')->name('create');
        Route::post('store', 'UserController@store')->name('store');
        Route::group(['prefix' => '{user}'], function () {
            Route::get('edit', 'UserController@edit')->name('edit');
            Route::get('delete', 'UserController@delete')->name('delete');
        });
    });

    //Articles
    Route::group(['prefix' => 'articles', 'as' => 'articles.', 'namespace' => 'Article'], function () {
        Route::get('/', 'ArticleController@index')->name('index');
        Route::get('create', 'ArticleController@create')->name('create');
        Route::post('store', 'ArticleController@store')->name('store');
        Route::group(['prefix' => '{article}'], function () {
            Route::get('edit', 'ArticleController@edit')->name('edit');
            Route::get('delete', 'ArticleController@delete')->name('delete');
        });
    });

    //Vacancies
    Route::group(['prefix' => 'vacancies', 'as' => 'vacancies.', 'namespace' => 'Vacancy'], function () {
        Route::group(['prefix' => 'directions', 'as' => 'directions.'], function () {
            Route::get('/', 'DirectionController@index')->name('index');
            Route::get('create', 'DirectionController@create')->name('create');
            Route::post('store', 'DirectionController@store')->name('store');
            Route::group(['prefix' => '{direction}'], function () {
                Route::get('edit', 'DirectionController@edit')->name('edit');
                Route::get('delete', 'DirectionController@delete')->name('delete');
            });
        });

        Route::get('/', 'VacancyController@index')->name('index');
        Route::get('create', 'VacancyController@create')->name('create');
        Route::post('store', 'VacancyController@store')->name('store');
        Route::group(['prefix' => '{vacancy}'], function () {
            Route::get('edit', 'VacancyController@edit')->name('edit');
            Route::get('delete', 'VacancyController@delete')->name('delete');
        });
    });

    //Projects
    Route::group(['prefix' => 'projects', 'as' => 'projects.', 'namespace' => 'Project'], function () {
        Route::group(['prefix' => 'options', 'as' => 'options.'], function () {
            Route::get('/', 'OptionController@index')->name('index');
            Route::get('create', 'OptionController@create')->name('create');
            Route::post('store', 'OptionController@store')->name('store');
            Route::group(['prefix' => '{option}'], function () {
                Route::get('edit', 'OptionController@edit')->name('edit');
                Route::get('delete', 'OptionController@delete')->name('delete');
            });
        });

        Route::get('/', 'ProjectController@index')->name('index');
        Route::get('create', 'ProjectController@create')->name('create');
        Route::post('store', 'ProjectController@store')->name('store');
        Route::group(['prefix' => '{project}'], function () {
            Route::get('edit', 'ProjectController@edit')->name('edit');
            Route::get('delete', 'ProjectController@delete')->name('delete');
        });
    });

    //Commands
    Route::group(['prefix' => 'commands', 'as' => 'commands.'], function () {
        Route::get('/', 'CommandController@index')->name('index');
        Route::get('create', 'CommandController@create')->name('create');
        Route::post('store', 'CommandController@store')->name('store');
        Route::group(['prefix' => '{command}'], function () {
            Route::get('edit', 'CommandController@edit')->name('edit');
            Route::get('delete', 'CommandController@delete')->name('delete');
        });
    });

    //Histories
    Route::group(['prefix' => 'histories', 'as' => 'histories.'], function () {
        Route::get('/', 'HistoryController@index')->name('index');
        Route::get('create', 'HistoryController@create')->name('create');
        Route::post('store', 'HistoryController@store')->name('store');
        Route::group(['prefix' => '{history}'], function () {
            Route::get('edit', 'HistoryController@edit')->name('edit');
            Route::get('delete', 'HistoryController@delete')->name('delete');
        });
    });

    //Texts
    Route::group(['prefix' => 'texts', 'as' => 'texts.'], function () {
        Route::get('/', 'TextController@index')->name('index');
        Route::post('store', 'TextController@store')->name('store');
        Route::group(['prefix' => '{text}'], function () {
            Route::get('edit', 'TextController@edit')->name('edit');
        });
    });

//    //Pages
//    Route::group(['prefix' => 'pages', 'as' => 'pages.'], function () {
//        Route::get('/', 'PageController@index')->name('index');
//        Route::get('create', 'PageController@create')->name('create');
//        Route::post('store', 'PageController@store')->name('store');
//        Route::group(['prefix' => '{page}'], function () {
//            Route::get('edit', 'PageController@edit')->name('edit');
//            Route::get('delete', 'PageController@delete')->name('delete');
//        });
//    });

    //Settings
    Route::group(['prefix' => 'settings', 'as' => 'settings.', 'namespace' => 'Setting'], function () {
        Route::get('edit', 'SettingController@edit')->name('edit');
        Route::post('store', 'SettingController@store')->name('store');

        Route::group(['prefix' => 'translation', 'as' => 'translation.'], function () {
            Route::get('/', 'TranslationController@index')->name('index');
            Route::post('/', 'TranslationController@store')->name('store');
        });

        //Countries
        Route::group(['prefix' => 'countries', 'as' => 'countries.'], function () {
            Route::get('/', 'CountryController@index')->name('index');
            Route::get('create', 'CountryController@create')->name('create');
            Route::post('store', 'CountryController@store')->name('store');
            Route::group(['prefix' => '{country}'], function () {
                Route::get('edit', 'CountryController@edit')->name('edit');
                Route::get('delete', 'CountryController@delete')->name('delete');
            });
        });

        //Cities
        Route::group(['prefix' => 'cities', 'as' => 'cities.'], function () {
            Route::get('/', 'CityController@index')->name('index');
            Route::get('create', 'CityController@create')->name('create');
            Route::post('store', 'CityController@store')->name('store');
            Route::group(['prefix' => '{city}'], function () {
                Route::get('edit', 'CityController@edit')->name('edit');
                Route::get('delete', 'CityController@delete')->name('delete');
            });
        });
    });
});

app/Models/Image.php
<?php

namespace App\Models;

use Spatie\Glide\GlideImage;
use Illuminate\Database\Eloquent\Model;
use File;

class Image extends Model
{
    protected $table = 'images';

    protected $fillable = ['path', 'main', 'type', 'description_ru', 'description_en', 'order'];

    public function imageable()
    {
        return $this->morphTo();
    }

    public function scopeMain($query)
    {
        return $query->where('main', '=', 1);
    }

    public function scopeOfType($query, $type)
    {
        return $query->where('type', '=', $type);
    }

    public function load($params = 'original', $model = null)
    {
        if (!$model) $model = $this->imageable;
        $path = $model->getImagePath($this->type, $params, $this->path);

        if (!File::exists($path)) {
            if ($params != 'original') {
                $path = $this->resize($params, $model);
            }
        }

        $path = str_replace('\\', '/', $path);
        return '/' . $path;
    }

    public function resize($params, $model = null)
    {
        if (!$model) $model = $this->imageable;
        $path = $model->getImagePath($this->type, 'original', $this->path);
        if (!File::exists($path)) {
            return $path;
        }
        $paramsArray = $model::getImageParams($this->type, $params);
        if (empty($paramsArray)) {
            return $model->getImagePath($this->type, 'original', $this->path);
        }
        $newPath = $model->getImagePath($this->type, $params);
        $newPathWithFile = $model->getImagePath($this->type, $params, $this->path);
        if (!File::exists($newPath)) {
            File::makeDirectory($newPath, 0777, true);
        }

        (new GlideImage())->load($path)
            ->useAbsoluteSourceFilePath()
            ->modify($paramsArray)
            ->save($newPathWithFile);

        return $newPathWithFile;
    }

    public static function slug2Model($slug)
    {
        $modelsPath = config('panel.models_path');
        $classElements = explode('-', $slug);
        $classElements = array_map(function ($value) {
            return studly_case($value);
        }, $classElements);
        $class = implode('\\', $classElements);
        $class = $modelsPath . '\\' . $class;
        $class = ltrim($class, '\\');
        return $class;
    }

    public function getTitleAttribute()
    {
        return \LaravelLocalization::getCurrentLocale() == 'ru' ? $this->description_ru : $this->description_en;
    }

}

resources/views/admin/partials/breadcrumbs.blade.php
@if ($breadcrumbs)
    <ul class="breadcrumb__list">
        @foreach ($breadcrumbs as $breadcrumb)
            @if ($breadcrumb->url && !$loop->last)
                <li class="breadcrumb__item"><a href="{{ $breadcrumb->url }}" class="breadcrumb__link pjax-link">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="breadcrumb__item"><div class="breadcrumb__link">{{ $breadcrumb->title }}</div></li>
            @endif
        @endforeach
    </ul>
@endif

resources/views/admin/partials/menu.blade.php
<li class="{{ str_contains(request()->url(), route('admin.articles.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.articles.index') }}" class="pjax-link">
        <i class="fa fa-newspaper-o"></i>
        <span class="text">  {{ __('admin.articles.title') }}</span>
    </a>
</li>

<li class="{{ str_contains(request()->url(), route('admin.texts.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.texts.index') }}" class="pjax-link">
        <i class="fa fa-font"></i>
        <span class="text"> {{ __('admin.texts.title') }}</span>
    </a>
</li>

<li class="sub-menu {{ str_contains(request()->url(), route('admin.vacancies.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.vacancies.index') }}">
        <i class="fa fa-bullhorn"></i>
        <span class="nav-label"> {{ __('admin.vacancies.title') }}</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="nav nav-second-level collapse {{ str_contains(request()->url(), route('admin.vacancies.index')) ? 'in' : '' }}">
        <li class="{{
            str_contains(request()->url(), route('admin.vacancies.index'))
            && !str_contains(request()->url(), route('admin.vacancies.directions.index'))
            ? 'active' : '' }}">
            <a href="{{ route('admin.vacancies.index')  }}" class="pjax-link"> {{ __('admin.vacancies.title') }}</a>
        </li>
        <li class="{{ str_contains(request()->url(), route('admin.vacancies.directions.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.vacancies.directions.index')  }}" class="pjax-link"> {{ __('admin.vacancies.directions.title') }}</a>
        </li>
    </ul>
</li>

<li class="sub-menu {{ str_contains(request()->url(), route('admin.projects.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.projects.index') }}">
        <i class="fa fa-briefcase"></i>
        <span class="nav-label"> {{ __('admin.projects.title') }}</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="nav nav-second-level collapse {{ str_contains(request()->url(), route('admin.projects.index')) ? 'in' : '' }}">
        <li class="{{
            str_contains(request()->url(), route('admin.projects.index'))
            && !str_contains(request()->url(), route('admin.projects.options.index'))
            ? 'active' : '' }}">
            <a href="{{ route('admin.projects.index')  }}" class="pjax-link"> {{ __('admin.projects.title') }}</a>
        </li>
        <li class="{{ str_contains(request()->url(), route('admin.projects.options.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.projects.options.index')  }}" class="pjax-link"> {{ __('admin.projects.options.title') }}</a>
        </li>
    </ul>
</li>

<li class="{{ str_contains(request()->url(), route('admin.commands.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.commands.index') }}" class="pjax-link">
        <i class="fa fa-users"></i>
        <span class="text">  {{ __('admin.commands.title') }}</span>
    </a>
</li>

<li class="{{ str_contains(request()->url(), route('admin.histories.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.histories.index') }}" class="pjax-link">
        <i class="fa fa-history"></i>
        <span class="text">  {{ __('admin.histories.title') }}</span>
    </a>
</li>


{{--<li class="{{ str_contains(request()->url(), route('admin.pages.index')) ? 'active' : '' }}">--}}
    {{--<a href="{{ route('admin.pages.index') }}" class="pjax-link">--}}
        {{--<i class="fa fa-file"></i>--}}
        {{--<span class="text"> {{ __('admin.pages.title') }}</span>--}}
    {{--</a>--}}
{{--</li>--}}

<li class="{{ str_contains(request()->url(), route('admin.users.index')) ? 'active' : '' }}">
    <a href="{{ route('admin.users.index') }}" class="pjax-link">
        <i class="fa fa-user"></i>
        <span class="text">  {{ __('admin.users.title') }}</span>
    </a>
</li>

<li class="sub-menu {{ str_contains(request()->url(), route('admin.settings.edit')) ? 'active' : '' }}">
    <a href="{{ route('admin.settings.edit') }}">
        <i class="fa fa-cog"></i>
        <span class="nav-label"> {{ __('admin.settings.title') }}</span>
        <span class="fa arrow"></span>
    </a>
    <ul class="nav nav-second-level collapse">
        <li class="{{ str_contains(request()->url(), route('admin.settings.edit')) ? 'active' : '' }}">
            <a href="{{ route('admin.settings.edit') }}" class="pjax-link"> {{ __('admin.settings.title') }} </a>
        </li>

        <li class="{{ str_contains(request()->url(), route('admin.settings.countries.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.settings.countries.index') }}" class="pjax-link"> {{ __('admin.settings.countries.title') }} </a>
        </li>

        <li class="{{ str_contains(request()->url(), route('admin.settings.cities.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.settings.cities.index') }}" class="pjax-link"> {{ __('admin.settings.cities.title') }} </a>
        </li>

        <li class="{{ str_contains(request()->url(), route('admin.settings.translation.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.settings.translation.index') }}" class="pjax-link"> {{ __('admin.settings.translation.index') }} </a>
        </li>
    </ul>
</li>

<hr>

<li>
    <a href="{{ route('index.home') }}" target="_blank">
        <i class="fa fa-sign-in"></i>
        <span class="text"> Перейти на сайт</span>
    </a>
</li>

resources/views/admin/partials/navbar.blade.php
<div class="row border-bottom">
    <nav class="navbar-static-top" role="navigation">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-warning " href="#"><i class="fa fa-bars"></i> </a>
            {{--{!! Form::open(['route' => 'admin.sync1c', 'class' => 'input-group-btn add-button-top js_form-ajax', 'style' => 'margin-left: 15px;'])  !!}--}}
                {{--<button class="btn btn-sm btn-white" type="submit"><span class="fa fa-spinner"></span> Синхронизация 1C</button>--}}
            {{--{!! Form::close() !!}--}}
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="{{ action('Admin\\Auth\\LoginController@logout') }}">
                    <i class="fa fa-sign-out"></i> Выйти
                </a>
            </li>
        </ul>
    </nav>
</div>

resources/views/admin/partials/pagination.blade.php
{{ $paginator->appends(request()->except('_pjax'))->links() }}